name: Monthly BRL to USD Tracker

on:
  schedule:
    - cron: '0 17 28 * *'  # Runs on the 26th day of each month at 17:00 UTC (14:00 UTC-3)
  workflow_dispatch:      # Allows manual runs from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests google-api-python-client google-auth google-auth-oauthlib python-dotenv

      - name: Run currency script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          PIX_KEY: ${{secrets.PIX_KEY}}
          SERVICE: ${{secrets.SERVICE}}
        run: python main.py
